site_name: exam slayer
site_url: http://127.0.0.1/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
plugins:
  - search
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Project manual: index.md
  - Design documentation:
    - Domain model: design/domain_model.md
    - Sequence diagrams: design/sequence_diagrams.md
    - Class diagrams: design/class_diagrams.md
  - Testing:
    - System test: system_test.md
    - Unit test: unit_test.md
  - Complete class diagram: class.md
  